- name: Remove neovim
  file:
    state: absent
    path: ~/.local/bin/nvim.appimage
  tags:
    - install
    - neovim

- name: Get Packer
  ansible.builtin.git:
    repo: 'https://github.com/wbthomason/packer.nvim'
    dest: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
  tags:
    - install
    - neovim

- name: Get nvim latest tag
  github_release:
    user: neovim
    repo: neovim
    action: latest_release
  register: nvim_latest
  tags:
    - install
    - neovim

- name: Grab nvim latest appimage
  ansible.builtin.get_url:
    url: "https://github.com/neovim/neovim/releases/download/{{ nvim_latest['tag'] }}/nvim.appimage"
    dest: ~/.local/bin/
    mode: a+x
  tags:
    - install
    - neovim

- name: Neovim Plugin Development 1
  become: true
  apt: name=luarocks
  tags:
    - install
    - neovim

- name: Neovim Plugin Development 2 luacheck
  become: true
  shell: luarocks install luacheck
  tags:
    - install
    - neovim
